Octaspire Core Manual
=====================
:author: www.octaspire.com
:lang: en
:toc:

Documentation for Octaspire Core library version 0.31.0

== About

*Octaspire Core* is a container, utf-8 and utility library written in standard *C99*.
It depends only on a C99 compiler and standard library.

Octaspire Core is used by some other Octaspire projects like 
http://www.octaspire.com/dern[Dern], http://www.octaspire.com/maze[Maze] and
http://www.octaspire.com/lightboard[Lightboard], but it should be usable on many
different platforms and projects where *region allocator* or
containers like *vector*, *hash-map*, *pair* or *utf-8 string* are needed.

Octaspire Core is licensed under the Apache License, Version 2.0. See file LICENSE
in the source distribution for more information.

Octaspire Core uses
http://semver.org[Semantic Versioning 2.0.0] version numbering scheme.
As long as the MAJOR version number is zero anything can change at any time,
even in backwards incompatible manner.

[NOTE]
This library is not yet finished, and is still a work in progress to some extent. Unit tests
and use in projects like Dern, Maze and Lightboard have helped to catch and fix quite a many bugs
already, but there are still some features not yet implemented and probably bugs not yet fixed.
Also, English in not my native language, so please bear with me, when reading this documentation.

[NOTE]
This documentation is work in progress.

Core uses
http://semver.org[Semantic Versioning 2.0.0] version numbering scheme.
As long as the MAJOR version number is zero anything can change at any time,
even in backwards incompatible manner.

++++
<script type="text/javascript" src="https://asciinema.org/a/120956.js" id="asciicast-120956" async></script>
++++


== Building from source

=== Raspberry Pi, Debian and Ubuntu

To build Octaspire Core from source in Raspberry Pi, Debian or Ubuntu (16.04 LTS) system:

:source-highlighter: pygments
:pygments-style: colorful
:pygments-linenums-mode: inline
[source,bash]
----
sudo apt-get install cmake git
git clone https://github.com/octaspire/core.git
cd core/build
cmake ..
make
----

=== Arch Linux

To build on Arch Linux (Arch Linux ARM) system:

:source-highlighter: pygments
:pygments-style: colorful
:pygments-linenums-mode: inline
[source,bash]
----
sudo pacman -S cmake git gcc make
git clone https://github.com/octaspire/core.git
cd core/build
cmake ..
make
----

=== Haiku

To build on Haiku (Version Walter (Revision hrev51127) x86_gcc2):

:source-highlighter: pygments
:pygments-style: colorful
:pygments-linenums-mode: inline
[source,bash]
----
pkgman install gcc_x86 cmake_x86
git clone https://github.com/octaspire/core.git
cd core/build
CC=gcc-x86 cmake ..
make
----

=== FreeBSD
To build on FreeBSD (FreeBSD-11.0-RELEASE-arm-armv6-RPI2) system:

:source-highlighter: pygments
:pygments-style: colorful
:pygments-linenums-mode: inline
[source,bash]
----
sudo pkg install git cmake
git clone https://github.com/octaspire/core.git
cd core/build
cmake ..
make
----

=== MINIX 3
To build on MINIX 3 (minix_R3.3.0-588a35b) system:

:source-highlighter: pygments
:pygments-style: colorful
:pygments-linenums-mode: inline
[source,bash]
----
su root
pkgin install cmake clang binutils git-base
exit
git clone git://github.com/octaspire/core
cd core/build
cmake ..
make
----

=== Other systems

On different systems the required commands can vary. In any case, You should install
a *C compiler*, *cmake* and *git*.

=== Running unit tests

This is all there should be to it; when make finishes, everything should be ready.

To run the unit tests:

:source-highlighter: pygments
:pygments-style: colorful
:pygments-linenums-mode: inline
[source,bash]
----
test/octaspire-core-test-runner
----

[NOTE]
Man pages are not ready yet.


== Using the amalgamated source

*etc*-directory of the source distribution contains amalgamated version
of the source code. All the headers, implementation files and unit tests
are concatenated with a script into a single file. This one file
is all that is needed to use Octaspire Core, and by using compiler
flags the same file can be compiled into a unit test runner.

TODO

== Quick tour of library features

Here we take a quick look at the features of the library.

=== Naming

C doesn't have namespaces. To prevent name collisions, all names in the library
are prefixed with *octaspire_*. For example, *octaspire_container_utf8_string_t*
is the string type and *octaspire_container_utf8_string_new* is one of the functions
that create new strings. *octaspire_container_vector_t* is the vector type and
*octaspire_container_hash_map_t* is the hash-map type.

These names can be pretty long, and quite annoying to write in the long run. I personally
like to use the abbrevation features of vi/vim and emacs editors. You can see this setup
in my https://github.com/octaspire/dotfiles[dotfiles] for nvi, vim and emacs editors. Your
favorite editor or IDE might have similar functionality also available.

So, I can write *ocus* and hit the spacebar to get *octaspire_container_utf8_string_*.
The table below lists some of the abbrevations I use:

[width="50%"]
|===============
|ocus   | octaspire_container_utf8_string_
|ocve   | octaspire_container_vector_
|ochm   | octaspire_container_hash_map_
|ochme  | octaspire_container_hash_map_element_
|===============


=== Allocator with and without regions

TODO

=== UTF-8 Strings

:source-highlighter: pygments
:pygments-style: colorful
:pygments-linenums-mode: inline
[source,c]
.string-example.c
----
include::../examples/string-example.c[]
----

=== Vector

:source-highlighter: pygments
:pygments-style: colorful
:pygments-linenums-mode: inline
[source,c]
.vector-example.c
----
include::../examples/vector-example.c[]
----

=== Pair

TODO

=== Hash map

:source-highlighter: pygments
:pygments-style: colorful
:pygments-linenums-mode: inline
[source,c]
.hash-map-example.c
----
include::../examples/hash-map-example.c[]
----

=== Input streams from memory and files

TODO

=== Lower level helpers

TODO

