Octaspire Core Manual
=====================
:author: www.octaspire.com
:lang: en
:toc:

== About

*Octaspire Core* is a container, utf-8 and utility library written in standard *C99*.
It depends only on a C99 compiler and standard library.

Octaspire Core is used by some other Octaspire projects like 
http://www.octaspire.com/dern[Dern] and https://github.com/octaspire/maze[Maze],
but it should be usable on many different platforms and projects where *region allocator* or
containers like *vector*, *hash-map*, *pair* or *utf-8 string* are needed.

Octaspire Core is licensed under the Apache License, Version 2.0. See file LICENSE
in the source distribution for more information.

[NOTE]
This library is not yet finished, and is still a work in progress to some extent. Unit tests
and use in projects like Dern and Maze have helped to catch and fix quite a many bugs already,
but there are still some features not yet implemented and probably bugs not yet fixed.
Also, English in not my native language, so please bear with me, when reading this documentation.

[NOTE]
This documentation is work in progress.


== Building from source

To build Octaspire Core from source in Raspberry Pi, Debian or Ubuntu (16.04 LTS) system:

:source-highlighter: pygments
:pygments-style: colorful
:pygments-linenums-mode: inline
[source,bash]
----
sudo apt-get install cmake git
git clone https://github.com/octaspire/core.git
cd core/build
cmake ..
make
----

To build on Arch Linux (Arch Linux ARM) system:

:source-highlighter: pygments
:pygments-style: colorful
:pygments-linenums-mode: inline
[source,bash]
----
sudo pacman -S cmake git gcc make
git clone https://github.com/octaspire/core.git
cd core/build
cmake ..
make
----

On different systems the required commands can vary. In any case, You should install
a *C compiler*, *cmake* and *git*.

This is all there should be to it; when make finishes, everything should be ready.

To run the unit tests:

:source-highlighter: pygments
:pygments-style: colorful
:pygments-linenums-mode: inline
[source,bash]
----
test/octaspire-core-test-runner
----

[NOTE]
Man pages are not ready yet.

== Quick tour of library features

Here we take a quick look at the features of the library.

=== Naming

C doesn't have namespaces. To prevent name collisions, all names in the library
are prefixed with *octaspire_*. For example, *octaspire_container_utf8_string_t*
is the string type and *octaspire_container_utf8_string_new* is one of the functions
that create new strings. *octaspire_container_vector_t* is the vector type and
*octaspire_container_hash_map_t* is the hash-map type.

These names can be pretty long, and quite annoying to write in the long run. I personally
like to use the abbrevation features of vi/vim and emacs editors. You can see this setup
in my https://github.com/octaspire/dotfiles[dotfiles] for nvi, vim and emacs editors. Your
favorite editor or IDE might have similar functionality also available.

So, I can write *ocus* and hit the spacebar to get *octaspire_container_utf8_string_*.
The table below lists some of the abbrevations I use:

[width="50%"]
|===============
|ocus   | octaspire_container_utf8_string_
|ocve   | octaspire_container_vector_
|ochm   | octaspire_container_hash_map_
|ochme  | octaspire_container_hash_map_element_
|===============


=== Allocator with and without regions

TODO

=== UTF-8 Strings

TODO

:source-highlighter: pygments
:pygments-style: colorful
:pygments-linenums-mode: inline
[source,c]
.string-example.c
----
include::../examples/string-example.c[]
----

=== Vector

TODO

:source-highlighter: pygments
:pygments-style: colorful
:pygments-linenums-mode: inline
[source,c]
.vector-example.c
----
include::../examples/vector-example.c[]
----

=== Pair

TODO

=== Hash map

TODO

=== Input streams from memory and files

TODO

=== Lower level helpers

TODO

